console.log("-----------")
console.log("Rise and Shine")
console.log("-----------")
console.log("Welcome to the world of JavaScript!")  
console.log("-----------")
console.log("Have a great day!")
console.log("-----------")
console.log("End of message")
console.log("-----------")
console.log("Goodbye!")